name: "Security checks"

on:
  pull_request:
    types: [opened, synchronize, reopened]

  schedule:
    - cron: '0 2 * * 0'

jobs:
  code-ql:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.event_name == 'schedule'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}

      - if: github.event_name == 'schedule'
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          config-file: ./.github/codeql/config.yml
          languages: java

      - if: github.event_name == 'pull_request'
        name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - run: |
          env
          mkdir ~/.m2
          #printf "${{ secrets.HELLO_WORLD }}" > ~/.m2/settings.xml

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1